### PR TITLE
chore(gulp): Fix build behavior by returning stream.

### PR DESCRIPTION
**Pull request by hutson**
Related to #1

### CODE REVIEW

**Comment by hutson** [comment]
Linting errors. Seems the lint rules were updated in the `jscs` package, breaking this build.

May want to use https://nightli.es/ to re-build you project on a regular basis so that these breaking changes are caught.

**Comment by daxelrod** [comment]
Thank you for catching this! :+1:

I will fix the lint errors within the next few days, and then accept this.

As for fixing the problem of dependency updates breaking things, I think Nightlies might be my best option. Ideally I'd like to solve that via shrinkwrap. However, I'd also like to start using [Greenkeeper](http://greenkeeper.io) which is [incompatible with shrinkwrap](https://github.com/greenkeeperio/greenkeeper/issues/96). That also wouldn't help in this case, because devDependencies aren't included in shrinkwraps anyway.

**Comment by hutson** [comment]
@daxelrod technically you can run `npm shrinkwrap --dev` to record both runtime dependencies and dev dependencies.

As this is a CLI, I can see why you would want to shrinkwrap dependencies.

Though you may not want to shrinkwrap dev dependencies. If you shrinkwrapped those, they would probably be installed along with your dependencies when someone installed your CLI tool.

Also, shrinkwrapping your dependencies is probably sufficient for what you want to do, guarantee that each re-installation of a version will behave the same, which would be technically true with shrinkwrapped dependencies for your CLI tool. Whether the lint rules have changed doesn't changed how the project will run.

**Comment by daxelrod** [comment]
Ok, f9060e0 should fix the linting problem. Please rebase.

**Comment by hutson** [comment]
Rebased

**Pull request merged**
